Repository carolinaknoll/awesome-gamified, pull requests merged in 2019-10, with the labels that each got.

#15 Refactor and allow requests for differently cased README files
  src/components/topic-list.js
Labels: Hacktoberfest

#17 item count on panel
  src/assets/styles/saved-items.css
  src/components/saved-items.js
Labels: Hacktoberfest

#19 Center readme introduction
  README.md
Labels: Awesome Gamified 2.0, Difficulty: Starter :shield:, Hacktoberfest

#20 Display zero when a saved items list is empty
  src/components/saved-items.js
Labels: Awesome Gamified 2.0, Difficulty: Starter :shield:, Fixed :tada:, Hacktoberfest

#25 added a loader when loading readme files
  src/assets/styles/loader.css
  src/components/loader.js
  src/components/topic-list.js
Labels: Awesome Gamified 2.0, Hacktoberfest

#27 Created search input to search for topics
  package-lock.json
  src/assets/styles/searchbar.css
  src/components/searchbar.js
  src/components/subjects-tree.js
  src/containers/awesome-gamified.js
Labels: Hacktoberfest

#28 Center badge count and fix margins
  src/assets/styles/saved-items.css
Labels: Awesome Gamified 2.0, Difficulty: Starter :shield:, Hacktoberfest, Issue Taken :shield:

#29 Add clicked topic.name to page title
  src/containers/awesome-gamified.js
Labels: Awesome Gamified 2.0, Difficulty: Starter :shield:, Hacktoberfest
